version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: breakflow_postgres_db
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: StrongPassword123
      POSTGRES_DB: breakflow_db
      
    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
    name: breakflow-db-data